## Deploy command
## mkdocs gh-deploy --remote-branch master

site_name: "Takuto Maeda | 前田 拓人"
site_author: "Takuto Maeda"

site_url: https://tktmyd.github.io/

copyright: "Copyright &copy Takuto Maeda. All Rights Reserved"

docs_dir: "src"

site_dir: "docs"

use_directory_urls: true

theme:
  language: en
  name: material
  palette:
    scheme: default
    primary: teal
    accent: pink
  custom_dir:
    overrides
  features:
#    - navigation.sections
    - navigation.tabs
#    - navigation.expand

extra_css:
  - "https://fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "https://fonts.googleapis.com/css?family=Noto+Serif+JP"
  - "https://fonts.googleapis.com/css?family=Montserrat"
  - "https://fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"
  - "css/custom.css"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
        - ja

extra:
  analytics:
    provider: google
    property: G-Z7X3M6JBS8

markdown_extensions:
  - markdown.extensions.def_list
  - markdown.extensions.admonition
  - markdown.extensions.footnotes
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.codehilite:
      linenums: true
      use_pygments: true
  - pymdownx.arithmatex:
      preview: false
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - docs/icons
  - attr_list
  - markdown.extensions.def_list

extra_javascript:
  - mathjax-config.js
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
  - Home: index.md
  - CV:
      - English: cv-e.md
      - 日本語版: cv-j.md
  - Research: 
      - Publications | 論文 : pubs.md
      - Presentations | 研究発表 : presentations.md
      - Open Codes | ソフトウェア: opencodes.md
  - Education:
      - Lectures | 講義: lectures.md
      - Thesis | 指導学位論文: thesis.md
      - Seismological Laboratory: https://www.st.hirosaki-u.ac.jp/~seismolab/dw/doku.php
  - Outreach: 
      - Talks | 一般向け講演: outreach.md
      - Media | 取材: media.md
      - Movies: 
         - 2021-02-13 Off Fukushima: movies/2021-02-13.md
         - 2024-01-01 Noto Peninsula: movies/2024-01-01.md
      - Seismo Info | 地震の情報源: seismo-info.md
#  - Projects: https://www.st.hirosaki-u.ac.jp/~tktmyd/dw/doku.php/ja/projects
  